-- Migration 0001: initial Phase 1 schema.
--
-- Tables created here:
--   domains         — managed mail domains (primary + future custom domains)
--   users           — user accounts
--   user_keys       — user public PGP keys (server never holds private side)
--   addresses       — per-user email addresses (one or many per user)
--   sessions        — HTTP login sessions (cookie-based, server-side store)
--   invites         — invite tokens (operator-created via new-invite.sh)
--   messages        — stored RFC 5322 messages (metadata + blob ref)
--   known_keys      — per-user correspondent key cache
--
-- Design notes:
--   • UUIDs are generated by the server (gen_random_uuid()) for all PKs.
--   • All timestamps are timestamptz (UTC enforced by app layer too).
--   • Text fields that carry email addresses are lower-cased at insert time
--     by the application layer; the schema stores them as-is.
--   • Soft delete for messages is folder = 'trash'; the deleted_at column
--     records *when* the message was moved to trash so a purge worker can
--     age it out after the configured retention window (§11.5, default 30
--     days). Hard delete is a physical row deletion. The folder column is
--     the single signal that a message is in trash — list queries filter on
--     folder, not on deleted_at.
--   • The blob_sha256 column on messages references the content-addressed
--     file on disk; the file path is /blobs/sha256/<ab>/<cd>/<full-hash>.eml.

-- -------------------------------------------------------------------------
-- pgcrypto for gen_random_uuid() (available in the postgres:17 image)
-- -------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -------------------------------------------------------------------------
-- domains
-- -------------------------------------------------------------------------
CREATE TABLE domains (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    domain      TEXT        NOT NULL UNIQUE,
    is_primary  BOOLEAN     NOT NULL DEFAULT FALSE,
    -- owner_user_id is NULL for the primary domain (owned by the instance).
    -- For custom domains it references the user who registered it (Phase 3+).
    -- FK to users is added below via ALTER TABLE once users exists.
    owner_user_id UUID,
    verified_at TIMESTAMPTZ,
    wkd_active  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------------------
-- users
-- -------------------------------------------------------------------------
CREATE TABLE users (
    id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    -- primary_address is set after the address row is inserted; the
    -- circular dependency (users → addresses → users) is broken with
    -- DEFERRABLE constraints. See addresses table below.
    primary_address_id    UUID        UNIQUE, -- FK added after addresses table
    display_name          TEXT        NOT NULL DEFAULT '',
    login_hash            TEXT        NOT NULL, -- Argon2id hash of login passphrase
    quota_bytes           BIGINT      NOT NULL DEFAULT 5368709120, -- 5 GiB
    used_bytes            BIGINT      NOT NULL DEFAULT 0,
    totp_secret           TEXT,               -- NULL = TOTP not enabled
    suspended_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------------------------------------------------------
-- user_keys  (public PGP keys only — server never holds private side)
-- -------------------------------------------------------------------------
CREATE TABLE user_keys (
    id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fingerprint        TEXT        NOT NULL UNIQUE,
    armored_public_key TEXT        NOT NULL,
    -- algorithm is a short human-readable tag, e.g. "cv25519+ed25519" or "rsa4096"
    algorithm          TEXT        NOT NULL,
    is_active          BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_keys_user_id ON user_keys(user_id);

-- -------------------------------------------------------------------------
-- addresses
-- -------------------------------------------------------------------------
CREATE TABLE addresses (
    id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    domain_id              UUID        NOT NULL REFERENCES domains(id) ON DELETE RESTRICT,
    local_part             TEXT        NOT NULL, -- lower-cased, no plus-tag
    -- full address = local_part || '@' || domain; stored for query convenience
    address                TEXT        NOT NULL UNIQUE,
    is_alias               BOOLEAN     NOT NULL DEFAULT FALSE,
    alias_target_id        UUID        REFERENCES addresses(id) ON DELETE SET NULL,
    plus_addressing_enabled BOOLEAN    NOT NULL DEFAULT TRUE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT addresses_local_domain_unique UNIQUE (local_part, domain_id)
);

CREATE INDEX idx_addresses_user_id  ON addresses(user_id);
CREATE INDEX idx_addresses_address  ON addresses(address);

-- Now add the FK from users back to addresses (was deferred above).
ALTER TABLE users
    ADD CONSTRAINT fk_users_primary_address
    FOREIGN KEY (primary_address_id) REFERENCES addresses(id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- Also add the FK from domains to users (owner) now that users exists.
ALTER TABLE domains
    ADD CONSTRAINT fk_domains_owner
    FOREIGN KEY (owner_user_id) REFERENCES users(id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- -------------------------------------------------------------------------
-- reserved_local_parts  (postmaster, abuse, hostmaster, webmaster per §11.3)
-- -------------------------------------------------------------------------
-- These are enforced at the application layer; this table exists so we can
-- quickly check without hardcoding strings in queries.
CREATE TABLE reserved_local_parts (
    local_part TEXT PRIMARY KEY
);
INSERT INTO reserved_local_parts VALUES
    ('postmaster'), ('abuse'), ('hostmaster'), ('webmaster');

-- -------------------------------------------------------------------------
-- sessions  (server-side session store; see §11.2)
-- -------------------------------------------------------------------------
CREATE TABLE sessions (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT        NOT NULL UNIQUE, -- SHA-256 hex of the raw session token
    -- csrf_token is the synchronizer-token value for this session. Generated
    -- once at session creation, sent to the browser in the rookery_csrf
    -- cookie, and embedded in every form rendered during the session. Stable
    -- for the lifetime of the session so multiple open tabs do not invalidate
    -- each other's forms.
    csrf_token  TEXT        NOT NULL,
    -- last_seen is used for sliding-expiry; expires_at = last_seen + session_expiry_days
    last_seen   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
    -- Deliberately no ip_address or user_agent columns (§11.2 pseudonymity).
    -- Operators who enable log_connecting_ips in rookery.toml get these added
    -- at runtime by the application, NOT by schema change.
);

CREATE INDEX idx_sessions_user_id    ON sessions(user_id);
CREATE INDEX idx_sessions_token_hash ON sessions(token_hash);

-- -------------------------------------------------------------------------
-- invites  (operator-created via new-invite.sh; see §11.8)
-- -------------------------------------------------------------------------
CREATE TABLE invites (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    token       TEXT        NOT NULL UNIQUE, -- URL-safe random token
    expires_at  TIMESTAMPTZ,                 -- NULL = no expiry
    used_at     TIMESTAMPTZ,
    used_by_id  UUID        REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_invites_token ON invites(token);

-- -------------------------------------------------------------------------
-- messages  (stored RFC 5322 messages; see §11.5)
-- -------------------------------------------------------------------------
CREATE TABLE messages (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- thread_id groups messages by In-Reply-To/References; derived by app layer.
    thread_id        UUID,
    -- folder is a virtual view: inbox | sent | drafts | trash | bounced
    folder           TEXT        NOT NULL DEFAULT 'inbox',
    from_address     TEXT        NOT NULL,
    -- to_addresses and cc_addresses are MIME header values (NOT envelope recipients).
    -- BCC is never stored in queryable columns — only present in the raw blob.
    to_addresses     TEXT[]      NOT NULL DEFAULT '{}',
    cc_addresses     TEXT[]      NOT NULL DEFAULT '{}',
    subject          TEXT        NOT NULL DEFAULT '',
    message_date     TIMESTAMPTZ NOT NULL,
    size_bytes       BIGINT      NOT NULL DEFAULT 0,
    blob_sha256      TEXT        NOT NULL, -- content-addressed file on disk
    is_read          BOOLEAN     NOT NULL DEFAULT FALSE,
    is_starred       BOOLEAN     NOT NULL DEFAULT FALSE,
    -- security_state: pgp_encrypted | pgp_signed_plaintext | plaintext
    security_state   TEXT        NOT NULL DEFAULT 'plaintext',
    -- signature_status: verified | unknown_key | invalid | none
    signature_status TEXT        NOT NULL DEFAULT 'none',
    has_attachments  BOOLEAN     NOT NULL DEFAULT FALSE,
    -- deleted_at is the timestamp at which the message was moved to trash.
    -- Set together with folder = 'trash' (never independently). Used by the
    -- purge worker to age messages out after the configured trash retention
    -- window. List queries do NOT filter on this column — they filter on
    -- folder. The two are kept consistent by the application layer.
    deleted_at       TIMESTAMPTZ,
    received_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_messages_user_id    ON messages(user_id);
CREATE INDEX idx_messages_folder     ON messages(user_id, folder);
CREATE INDEX idx_messages_thread_id  ON messages(thread_id) WHERE thread_id IS NOT NULL;
CREATE INDEX idx_messages_deleted_at ON messages(deleted_at) WHERE deleted_at IS NOT NULL;

-- -------------------------------------------------------------------------
-- known_keys  (per-user correspondent key cache; see §8 / resource 7)
-- -------------------------------------------------------------------------
-- Keyed by (user_id, fingerprint) — not by address — so that key history
-- survives rotation (a single address can have multiple entries over time).
CREATE TABLE known_keys (
    id                 UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    address            TEXT        NOT NULL,
    fingerprint        TEXT        NOT NULL,
    armored_public_key TEXT        NOT NULL,
    -- source: auto_attach | wkd | keyserver | manual
    source             TEXT        NOT NULL DEFAULT 'auto_attach',
    first_seen_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT known_keys_user_fingerprint_unique UNIQUE (user_id, fingerprint)
);

CREATE INDEX idx_known_keys_user_id ON known_keys(user_id);
CREATE INDEX idx_known_keys_address ON known_keys(user_id, address);
